### ISSUE TITLE
em. to  .stl

### ISSUE THREAD

**Issue by karine-jan** [builab/subtomo2Chimera#4]
Thank you so much for this script. I was wondering if you could also add .em file format to the [dynamotable2ChimeraX.py] since unlike Relion the averages from the Dynamo are in .em format. Or alternatively maybe you know some tools for em to mrc conversion. Thank you once again!

**Comment by builab** [comment]
To convert .em to .mrc, you can use:
- EMAN2 (e2proc3d.py vol.em vol.mrc)
- Bsoft (https://cbiit.github.io/Bsoft/#) (bimg vol.em vol.mrc)
The only thing to be very careful about is to make sure the pixel size of the converted .mrc file correct since .em format is terrible with pixel size information.

**Comment by karine-jan** [comment]
Great! thank you for your reply! I can add ChimeraX to this list as well :) Just did it. Also had issues with the pixel size. Thank you so much!
